### ISSUE TITLE
No payload, or more than one chunk of payload

### ISSUE THREAD

**Issue by zeeoale** [AnselmoVi/SubsTwitch#1]
Ciao!, come da oggetto ho configurato il bot con token, id e secret di twitch ma quando do il comando /start sul bot ricevo questo messaggio in console "No payload, or more than one chunk of payload" cosa devo fare?

**Comment by AnselmoVi** [comment]
Ciao, scusami per la tardiva risposta.
Hai risolto? Comunque ti da quel messaggio perché oltre a /start si aspetta
un ID che viene dato dal "bot" del canale Twitch che non ho configurato io.
Cerca "how pass data with /start telebot telegram" per ulteriori info

Il ven 8 ott 2021, 14:25 zeeoale ***@***.***> ha scritto:

**Comment by AnselmoVi** [comment]
Ho aggiornato direttamente il codice commentandolo con le dovute spiegazioni, spero sia utile.
